import { ProductListing } from "./interfaces";

export const products: ProductListing[] = [
  {
    id: 1,
    activeStatus: "active",
    title: "White T-shirt",
    description: "Soft cotton white t-shirt, size M. Barely worn.",
    seller: "justin123",
    price: 15.0,
    createdDatetime: "2025-05-01T10:00:00Z",
    updatedDatetime: "2025-05-01T10:00:00Z",
    expirationDatetime: null,
    category: "Clothing",
    condition: "Good",
    location: "Seattle, WA",
    isSold: false,
    image:
      "https://images.unsplash.com/photo-1714070700737-24acfe6b957c?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 2,
    activeStatus: "active",
    title: "Nike Air Jordans",
    description: "Red and black Nike Jordans. Only worn twice.",
    seller: "sneakerhead88",
    price: 110.0,
    createdDatetime: "2025-04-30T14:30:00Z",
    updatedDatetime: "2025-04-30T14:30:00Z",
    expirationDatetime: null,
    category: "Footwear",
    condition: "Like New",
    location: "Portland, OR",
    isSold: false,
    image:
      "https://images.unsplash.com/photo-1704919266475-aa6302e25209?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 3,
    activeStatus: "active",
    title: "2018 Macbook Pro",
    description: "15-inch MacBook Pro with 512GB SSD and 16GB RAM.",
    seller: "maclover",
    price: 950.0,
    createdDatetime: "2025-04-29T09:15:00Z",
    updatedDatetime: "2025-04-29T09:15:00Z",
    expirationDatetime: null,
    category: "Electronics",
    condition: "Good",
    location: "San Francisco, CA",
    isSold: false,
    image:
      "https://plus.unsplash.com/premium_photo-1681160405609-389cd83998d0?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8bWFjJTIwYm9va3xlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 4,
    activeStatus: "active",
    title: "Standing Desk",
    description: 'Adjustable standing desk, white finish, 48" x 24".',
    seller: "deskdealer",
    price: 130.0,
    createdDatetime: "2025-04-28T11:45:00Z",
    updatedDatetime: "2025-04-28T11:45:00Z",
    expirationDatetime: null,
    category: "Furniture",
    condition: "Like New",
    location: "Seattle, WA",
    isSold: false,
    image: "https://m.media-amazon.com/images/I/81AQ4oN9bNL.jpg",
  },
  {
    id: 5,
    activeStatus: "active",
    title: "Electric Guitar",
    description: "Fender Stratocaster with gig bag. Great condition.",
    seller: "musicman",
    price: 400.0,
    createdDatetime: "2025-04-27T16:20:00Z",
    updatedDatetime: "2025-04-27T16:20:00Z",
    expirationDatetime: null,
    category: "Musical Instruments",
    condition: "Good",
    location: "Tacoma, WA",
    isSold: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL066cQktmc_NrzppNM27t0Pmuojnd3PFFdQ&s",
  },
  {
    id: 6,
    activeStatus: "active",
    title: "Canon DSLR Camera",
    description: "Canon EOS Rebel T7 with 18-55mm lens.",
    seller: "shutterbug",
    price: 350.0,
    createdDatetime: "2025-04-26T13:00:00Z",
    updatedDatetime: "2025-04-26T13:00:00Z",
    expirationDatetime: null,
    category: "Photography",
    condition: "Like New",
    location: "Bellevue, WA",
    isSold: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSoRm0reh5wvNktygd7gzHLFrJiowNkw_HxQ&s",
  },
  {
    id: 7,
    activeStatus: "active",
    title: "Leather Office Chair",
    description: "Comfortable black leather chair. Minimal wear.",
    seller: "homeofficepro",
    price: 85.0,
    createdDatetime: "2025-04-25T17:45:00Z",
    updatedDatetime: "2025-04-25T17:45:00Z",
    expirationDatetime: null,
    category: "Furniture",
    condition: "Good",
    location: "Redmond, WA",
    isSold: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsQX2A6cro0dvR2YDWRtCV8Stcv5VAwfrYZA&s",
  },
  {
    id: 8,
    activeStatus: "active",
    title: "AirPods Pro",
    description: "Second-gen AirPods Pro with case. Clean and working.",
    seller: "techguy42",
    price: 150.0,
    createdDatetime: "2025-04-24T10:30:00Z",
    updatedDatetime: "2025-04-24T10:30:00Z",
    expirationDatetime: null,
    category: "Electronics",
    condition: "Like New",
    location: "Kirkland, WA",
    isSold: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDwK7g4qXoqDiUqA-LfBHv_uifjxryM5V8qg&s",
  },
  {
    id: 9,
    activeStatus: "active",
    title: "Mountain Bike",
    description: "29” Trek Marlin with front suspension. Great trail bike.",
    seller: "bikerbro",
    price: 480.0,
    createdDatetime: "2025-04-23T08:15:00Z",
    updatedDatetime: "2025-04-23T08:15:00Z",
    expirationDatetime: null,
    category: "Sports & Outdoors",
    condition: "Good",
    location: "Seattle, WA",
    isSold: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2UBOrjV_raOUTXeMqGI2uVe_bmQ5qnMbBrw&s",
  },
  {
    id: 10,
    activeStatus: "active",
    title: "IKEA Bookshelf",
    description: "Black 5-shelf IKEA Billy bookshelf in good condition.",
    seller: "ikeafan",
    price: 40.0,
    createdDatetime: "2025-04-22T12:00:00Z",
    updatedDatetime: "2025-04-22T12:00:00Z",
    expirationDatetime: null,
    category: "Furniture",
    condition: "Good",
    location: "Seattle, WA",
    isSold: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo9AUql84MSPVXggXT_jDp0aEObY2RUEOYXQ&s",
  },
];
