import { User } from "./interfaces";

export const users: User[] = [
  {
    id: 1,
    username: "justin123",
    email: "justin@example.com",
    passwordHash: "hashed_justin123",
    createdDatetime: "2024-01-10T09:00:00Z",
    updatedDatetime: "2025-04-25T11:00:00Z",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    name: "Justin Johnson",
    rating: 4.8,
    location: "Seattle, WA",
  },
  {
    id: 2,
    username: "sneakerhead88",
    email: "mikej@example.com",
    passwordHash: "hashed_mikej",
    createdDatetime: "2023-12-01T14:00:00Z",
    updatedDatetime: "2025-04-20T15:30:00Z",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    name: "Michael Jacobs",
    rating: 4.9,
    location: "Portland, OR",
  },
  {
    id: 3,
    username: "maclover",
    email: "sara.mac@example.com",
    passwordHash: "hashed_maclover",
    createdDatetime: "2022-11-15T10:00:00Z",
    updatedDatetime: "2025-03-01T08:45:00Z",
    image: "https://randomuser.me/api/portraits/women/60.jpg",
    name: "Sara Thompson",
    rating: 4.7,
    location: "San Francisco, CA",
  },
  {
    id: 4,
    username: "deskdealer",
    email: "kevin.desk@example.com",
    passwordHash: "hashed_deskdealer",
    createdDatetime: "2023-04-12T08:00:00Z",
    updatedDatetime: "2025-04-10T12:00:00Z",
    image: "https://randomuser.me/api/portraits/men/77.jpg",
    name: "Kevin Rodriguez",
    rating: 4.6,
    location: "Seattle, WA",
  },
  {
    id: 5,
    username: "musicman",
    email: "lee.music@example.com",
    passwordHash: "hashed_musicman",
    createdDatetime: "2023-07-01T11:15:00Z",
    updatedDatetime: "2025-04-01T09:30:00Z",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    name: "Lee Carter",
    rating: 4.5,
    location: "Tacoma, WA",
  },
  {
    id: 6,
    username: "shutterbug",
    email: "anna.camera@example.com",
    passwordHash: "hashed_shutterbug",
    createdDatetime: "2022-06-10T10:30:00Z",
    updatedDatetime: "2025-03-20T10:30:00Z",
    image: "https://randomuser.me/api/portraits/women/36.jpg",
    name: "Anna Ferguson",
    rating: 4.9,
    location: "Bellevue, WA",
  },
  {
    id: 7,
    username: "homeofficepro",
    email: "david.office@example.com",
    passwordHash: "hashed_homeofficepro",
    createdDatetime: "2023-05-15T07:45:00Z",
    updatedDatetime: "2025-02-28T14:00:00Z",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    name: "David Brooks",
    rating: 4.4,
    location: "Redmond, WA",
  },
  {
    id: 8,
    username: "techguy42",
    email: "tom.tech@example.com",
    passwordHash: "hashed_techguy42",
    createdDatetime: "2022-01-05T13:00:00Z",
    updatedDatetime: "2025-04-15T13:00:00Z",
    image: "https://randomuser.me/api/portraits/men/58.jpg",
    name: "Tom Kumar",
    rating: 4.7,
    location: "Kirkland, WA",
  },
  {
    id: 9,
    username: "bikerbro",
    email: "matt.bike@example.com",
    passwordHash: "hashed_bikerbro",
    createdDatetime: "2023-03-22T09:00:00Z",
    updatedDatetime: "2025-04-02T09:00:00Z",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    name: "Matt Rider",
    rating: 4.6,
    location: "Seattle, WA",
  },
  {
    id: 10,
    username: "ikeafan",
    email: "amy.shelf@example.com",
    passwordHash: "hashed_ikeafan",
    createdDatetime: "2022-09-30T16:00:00Z",
    updatedDatetime: "2025-04-05T16:00:00Z",
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    name: "Amy Wallace",
    rating: 4.3,
    location: "Seattle, WA",
  },
];
